# Generated by Django 5.0.4 on 2024-04-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price_main', models.CharField(max_length=50)),
                ('price_sale30', models.CharField(max_length=50)),
                ('price_sale50', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JarimaToifasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jarima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('band', models.ManyToManyField(to='backend.band')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.jarimatoifasi')),
            ],
        ),
    ]
