# Generated by Django 5.0.4 on 2024-05-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=150)),
                ('guvoxnomaNum', models.IntegerField(verbose_name=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('lifeTime', models.CharField(max_length=150)),
                ('givenName', models.CharField(max_length=150)),
                ('pasSeria', models.CharField(blank=True, max_length=2)),
                ('pasNum', models.IntegerField(blank=True, verbose_name=6)),
                ('guvoxnoma2Num', models.IntegerField(verbose_name=150)),
            ],
        ),
        migrations.CreateModel(
            name='AutoTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trueAnswer', models.IntegerField(default=0)),
                ('falseAnswer', models.IntegerField(default=0)),
                ('fullAnswer', models.IntegerField(default=0)),
                ('testID', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CarOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('traveled', models.IntegerField(verbose_name=150)),
                ('brand', models.CharField(max_length=150)),
                ('recommendedKm', models.IntegerField(verbose_name=150)),
                ('dailyKm', models.IntegerField(verbose_name=150)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=150)),
                ('departmentName', models.CharField(max_length=150)),
                ('departmentHead', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phoneNum', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('testDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MyDRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RestoreLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=150)),
                ('licenseNumber', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('phoneNum', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TexServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('phoneNum', models.CharField(max_length=13)),
                ('event', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TexServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('avtoNum', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('myService', models.CharField(max_length=150)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.serviceaddres')),
            ],
        ),
    ]
