# Generated by Django 5.0.4 on 2024-04-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Belgilar',
            new_name='YHQBelgilar',
        ),
        migrations.RenameModel(
            old_name='BelgiQoidalari',
            new_name='YHQBelgiQoidalari',
        ),
        migrations.RenameModel(
            old_name='Qoida',
            new_name='YHQQoida',
        ),
    ]
