# Generated by Django 5.0.4 on 2024-04-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarimaBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jarima',
            name='band',
        ),
        migrations.RemoveField(
            model_name='jarima',
            name='category',
        ),
        migrations.CreateModel(
            name='JarimaBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('url', models.FileField(upload_to='templates/Books')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.jarimabookcategory')),
            ],
        ),
        migrations.RenameModel(
            old_name='addresses',
            new_name='ServiceAddres',
        ),
        migrations.CreateModel(
            name='TexServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('avtoNum', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('myService', models.CharField(max_length=150)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.serviceaddres')),
            ],
        ),
        migrations.DeleteModel(
            name='JarimaBandi',
        ),
        migrations.DeleteModel(
            name='Jarima',
        ),
        migrations.DeleteModel(
            name='JarimaToifasi',
        ),
    ]
