# Generated by Django 5.0.4 on 2024-04-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jarimabookcategory_remove_jarima_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YHQQoidlarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='yhqqoidalarcategory',
            name='YHQQoidalar',
        ),
        migrations.RemoveField(
            model_name='jarimabook',
            name='url',
        ),
        migrations.AlterField(
            model_name='jarimabook',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jarimabookcategory',
            name='category',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='YHQQoidalarBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.FileField(upload_to='Books')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yhqqoidlarcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='YHQQoida',
        ),
        migrations.DeleteModel(
            name='YHQQoidalar',
        ),
        migrations.DeleteModel(
            name='YHQQoidalarCategory',
        ),
    ]
