# Generated by Django 5.0.4 on 2024-04-16 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
