# Generated by Django 5.0.4 on 2024-04-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_yhqqoida_id_alter_yhqqoida_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yhqbelgiqoidalari',
            name='BelgilarBolimi',
        ),
        migrations.RemoveField(
            model_name='yhqqoida',
            name='BelgiQoidalari',
        ),
        migrations.DeleteModel(
            name='YHQBelgilar',
        ),
        migrations.DeleteModel(
            name='YHQBelgiQoidalari',
        ),
        migrations.DeleteModel(
            name='YHQQoida',
        ),
    ]
