# Generated by Django 5.0.4 on 2024-04-19 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_yhqqoidlarcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yhqqoidalarbook',
            name='url',
        ),
        migrations.AddField(
            model_name='jarimabook',
            name='url',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Books'),
            preserve_default=False,
        ),
    ]
