# Generated by Django 5.0.4 on 2024-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_yhqqoidalarbook_url_jarimabook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('testDate', models.DateField()),
            ],
        ),
    ]
