# Generated by Django 5.0.4 on 2024-04-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=150)),
                ('guvoxnomaNum', models.IntegerField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('lifeTime', models.CharField(max_length=150)),
                ('givenName', models.CharField(max_length=150)),
                ('pasSeria', models.CharField(blank=True, max_length=2)),
                ('pasNum', models.IntegerField(blank=True, max_length=6)),
                ('guvoxnoma2Num', models.IntegerField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CarOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('traveled', models.IntegerField(verbose_name=150)),
                ('brand', models.CharField(max_length=150)),
                ('recommendedKm', models.IntegerField(verbose_name=150)),
                ('dailyKm', models.IntegerField(verbose_name=150)),
            ],
        ),
        migrations.CreateModel(
            name='TexServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('phoneNumber', models.IntegerField(max_length=50)),
                ('event', models.CharField(max_length=250)),
            ],
        ),
    ]
