# Generated by Django 5.0.4 on 2024-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_affidavit_caroil_texservicemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trueAnswer', models.IntegerField(default=0)),
                ('falseAnswer', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RestoreLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=150)),
                ('licenseNumber', models.IntegerField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('phoneNum', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='jarimabook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jarimabook',
            name='name',
        ),
        migrations.DeleteModel(
            name='JarimaBookCategory',
        ),
    ]
