# Generated by Django 5.0.4 on 2024-04-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_autotest_restorelicense_remove_jarimabook_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JarimaBook',
        ),
        migrations.AddField(
            model_name='autotest',
            name='fullAnswer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autotest',
            name='testID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='guvoxnoma2Num',
            field=models.IntegerField(verbose_name=150),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='guvoxnomaNum',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='pasNum',
            field=models.IntegerField(blank=True, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='restorelicense',
            name='licenseNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='texservicemessage',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='YHQQoidalarBook',
        ),
        migrations.DeleteModel(
            name='YHQQoidlarCategory',
        ),
    ]
