# Generated by Django 5.0.4 on 2024-04-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JarimaBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_uz', models.FileField(upload_to='Books')),
                ('url_ru', models.FileField(upload_to='Books')),
            ],
        ),
        migrations.CreateModel(
            name='YHQQoidlarCategoryRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryRu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='YHQQoidlarCategoryUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryUz', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='YHQQoidalarBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleUz', models.CharField(max_length=150)),
                ('titleRu', models.CharField(max_length=150)),
                ('url_ru', models.FileField(upload_to='Books/qoidalar')),
                ('url_uz', models.FileField(upload_to='Books/qoidalar')),
                ('categoryRu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.yhqqoidlarcategoryru')),
                ('categoryUz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.yhqqoidlarcategoryuz')),
            ],
        ),
    ]
