# Generated by Django 5.0.4 on 2024-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('carNamber', models.CharField(max_length=10)),
                ('texSeries', models.CharField(max_length=10)),
                ('texNum', models.CharField(max_length=10)),
                ('avtoMark', models.CharField(max_length=20)),
                ('avtoName', models.CharField(max_length=20)),
                ('avtoYear', models.IntegerField()),
                ('avtoEngine', models.CharField(max_length=50)),
                ('avtoColor', models.CharField(max_length=50)),
                ('docNumber', models.IntegerField()),
                ('docDate', models.DateField()),
                ('politicalNum', models.CharField(max_length=150)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('avtoBuyDate', models.DateField()),
                ('avtoPrice', models.CharField(max_length=150)),
                ('avtoCusov', models.CharField(max_length=150)),
                ('transmission', models.CharField(max_length=150)),
                ('vinCode', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
        ),
    ]
