# Generated by Django 5.0.4 on 2024-05-11 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addCar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='docNumber',
            new_name='carFullNum',
        ),
        migrations.RemoveField(
            model_name='car',
            name='avtoBuyDate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='avtoPrice',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carNamber',
        ),
        migrations.RemoveField(
            model_name='car',
            name='docDate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='email',
        ),
        migrations.RemoveField(
            model_name='car',
            name='politicalNum',
        ),
        migrations.RemoveField(
            model_name='car',
            name='userName',
        ),
        migrations.AddField(
            model_name='car',
            name='carNum',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='vinCode',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
