# Generated by Django 5.0.4 on 2024-04-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addCar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addCar',
            new_name='Car',
        ),
    ]
